name: Checks

on: [push]

jobs:
  test-Lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PYTHON_DEVS_USER }}
          password: ${{ secrets.PYTHON_DEVS_DOCKERHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Linting
        run: docker compose run --rm app sh -c "flake8"
